# Generated by Django 4.0.3 on 2022-03-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_rename_depature_train_departure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('coach_type', models.CharField(choices=[('1AC', '1A Class'), ('2AC', '2A Class'), ('3AC', '3A Class'), ('SL', 'Sleeper'), ('2S', '2S Class'), ('GEN', 'General')], default='GEN', max_length=4)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
        ),
    ]
