# Generated by Django 4.0.3 on 2022-03-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='boarded',
            field=models.BooleanField(default=True),
        ),
    ]
